"""Increase cover image size to Text

Revision ID: 82fc5bdd78ab
Revises: 99dc747a318d
Create Date: 2025-11-21 14:11:37.174568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82fc5bdd78ab'
down_revision = '99dc747a318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'annotation_layer', ['layer_id'], ['id'])

    with op.batch_alter_table('annotation_layer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_group', ['study_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'ebook', ['ebook_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('book_submission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['submitted_by_id'], ['id'])

    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.alter_column('cover_image_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['submitted_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('user_study_group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_group', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_study_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'study_group', ['group_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'user', ['user_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'user', ['creator_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'user', ['submitted_by_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'category', ['category_id'], ['id'], referent_schema='test')
        batch_op.alter_column('cover_image_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('book_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'user', ['submitted_by_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('annotation_layer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'ebook', ['ebook_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'study_group', ['study_group_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'user', ['creator_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'annotation_layer', ['layer_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'user', ['author_id'], ['id'], referent_schema='test')

    # ### end Alembic commands ###
